# Définition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template

[[routes]]
url = ""
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "nouvelle_partie"
controleur = "controleurs/nouvelle_partie.py"
template = "nouvelle_partie.html"

[[routes]]
url = "tours"
controleur = "controleurs/tours.py"
template = "tours.html"